# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-10-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='activity_image/None/no-img.jpg', upload_to='activity_image/')),
            ],
        ),
    ]
